### ISSUE TITLE
Smart / AutoComplete for all data entry

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/nodeVISTAClients#3]
# Autocomplete:  required for all menus and pick lists

List of 35 different ways to do autocompletion in Javascript:
- http://www.jqueryrain.com/2012/03/35-best-ajax-jquery-autocomplete-tutorial-plugin-with-examples/

**Comment by conorcaregraf** [comment]
this isn't an issue - it's BG information for JS client dev (move to ? docs?)

**Comment by rafael5** [comment]
Yes.  Background info.  Move to "note" (issue) in Docs

Rafael


*Rafael Richards MD MS*
*202-469-1527*
