### ISSUE TITLE
Restore fmQMCannedQueries

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/nodeVISTAClients#5]
## Restore fmQMCannedQueries

This is alternative access method and to demonstrate querying against MVDM data.

In nodeVISTA VM:    /home/vdp/FMQL/webclients:
fmBase.css
fmQMCannedQueries.js
fmQuery.html
fmRambler.html
fmSchema.html
fmUtils.js

**Comment by conorcaregraf** [comment]
put in FMQL issue in nodeVISTA
