### ISSUE TITLE
Console client:  needs to include full paths and guest/host designation in instructions

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/nodeVISTAClients#6]
## Console client:  instructions unclear

Instructions are unclear because it does not state 
1. Whether the command should be run from the host or the guest (VM) command line
2. Full path where the commands need to be executed

**Comment by sbruno81** [comment]
Modified README.md under console with the suggested changes.

**Comment by rafael5** [comment]
- ssh to nodeVISTA: supplemental info needed
   <https://github.com/vistadataproject/nodeVISTAClients/issues/8>
   #8 opened 24 seconds ago by rafael5
   <https://github.com/vistadataproject/nodeVISTAClients/issues?q=is%3Aissue+is%3Aopen+author%3Arafael5>

   -
   console client: connection refused on port 9030 but not 9000
   <https://github.com/vistadataproject/nodeVISTAClients/issues/7>
   #7 opened 7 minutes ago by rafael5
   <https://github.com/vistadataproject/nodeVISTAClients/issues?q=is%3Aissue+is%3Aopen+author%3Arafael5>

   -


Rafael


*Rafael Richards MD MS*
*202-469-1527*
