### ISSUE TITLE
console client:   connection refused on port 9030 

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/nodeVISTAClients#7]
console client: connection refused on port 9030, but not 9000

[console]$ curl http://10.2.2.100:9030
curl: (7) Failed to connect to 10.2.2.100 port 9030: Connection refused

[console]$ curl http://10.2.2.100:9000
Found. Redirecting to /schema

**Comment by sbruno81** [comment]
When you start the clientService server do you see the following output?

{"name":"clinicalService","hostname":"addgene-ubuntu-1604-vbox","pid":17213,"level":30,
    "msg":"Clinical Service listening on port 9030","time":"2017-02-27T20:22:47.506Z","v":0}

Also, are you leaving the clientService terminal open? You'll have to test connecting to it in another window.

**Comment by rafael5** [comment]
Yes. I do see this output indicating that the service is running. 

Note that by default the clientService is *not* running in the VM.  One has to

1a.  Start the service:  ssh to the guest VM and start it (per your instructions).
1b. Confirm service is running:  curl http://10.2.2.100:9030 -> then it gives correct response
2. Open a *separate* terminal on the host, and then  run   "node console.js"

**Comment by conorcaregraf** [comment]
it's not running the current demo - it will run in 1.2 by default just as rpcServer and fmqlServer do.
