### ISSUE TITLE
ssh to nodeVISTA:  supplemental info needed

### ISSUE THREAD

**Issue by rafael5** [vistadataproject/nodeVISTAClients#8]
### Current instructions:
$ ssh vagrant@10.2.2.100
$ vdp -l vdp
$ cd nodeVISTA/clinicalService
$ npm install
$ node index.js
{"name":"clinicalService","hostname":"addgene-ubuntu-1604-vbox","pid":17213,"level":30,
    "msg":"Clinical Service listening on port 9030","time":"2017-02-27T20:22:47.506Z","v":0}

### need to add login info for ssh:
$ ssh vagrant@10.2.2.100
=> password: vagrant
then within VM, need to add full path info:
$ cd  /home/vdp

but no nodeVISTA/clinicalService is at this path..

**Comment by sbruno81** [comment]
Fixed per suggestions above

**Comment by rafael5** [comment]
Thank you.

Still remain a port access issue to port 9030 (but not to 9000)

         console client: connection refused on port 9030
<https://github.com/vistadataproject/nodeVISTAClients/issues/7> bug
<https://github.com/vistadataproject/nodeVISTAClients/issues?q=is%3Aissue+is%3Aopen+label%3Abug>
#7 opened 15 hours ago by rafael5
<https://github.com/vistadataproject/nodeVISTAClients/issues?q=is%3Aissue+is%3Aopen+author%3Arafael5>
